1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [1]:
#please enter your code below this line.

import numpy as np
array = np.arange(0,9).reshape(3,3)
print("Sum of all elements in an array is : " ,np.sum(array))

Sum of all elements in an array is :  36


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [2]:
#please enter your code below this line.

import numpy as np
array = np.arange(0,9).reshape(3,3);
print("Row Sum of this array is : " ,np.sum(array,axis=1))
print("Column Sum of this array is : " ,np.sum(array,axis=0))

Row Sum of this array is :  [ 3 12 21]
Column Sum of this array is :  [ 9 12 15]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [3]:
#please enter your code belowthis line.

import numpy as np
array = np.arange(0,16).reshape(4,4)
print("Minimum value in the array is : ",np.min(array))
print("Maximum value in the array is : ",np.max(array))
print("Mean of values in the array is : ",np.mean(array))

Minimum value in the array is :  0
Maximum value in the array is :  15
Mean of values in the array is :  7.5


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [4]:
#please enter your code below this line.

import numpy as np
array = np.arange(0,100).reshape(10,10)
print(array)
print("7th row of the array is :",array[7])
print("Rows 4-8 of  the array is :",array[4:8])
print("Value at index 5,5 of array is :",[5,5])
print("The 5th column of matrix is : ",array[:,5])
print("Columns  2-5 of  the array is :",array[:,2:5])


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
7th row of the array is : [70 71 72 73 74 75 76 77 78 79]
Rows 4-8 of  the array is : [[40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]]
Value at index 5,5 of array is : [5, 5]
The 5th column of matrix is :  [ 5 15 25 35 45 55 65 75 85 95]
Columns  2-5 of  the array is : [[ 2  3  4]
 [12 13 14]
 [22 23 24]
 [32 33 34]
 [42 43 44]
 [52 53 54]
 [62 63 64]
 [72 73 74]
 [82 83 84]
 [92 93 94]]
