1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [1]:
#please provide your answer below this line.

import numpy as np
array = np.arange(0,9).reshape(3,3)
print(array)
array1 = np.arange(3,12).reshape(3,3)
print(array1)
array2= np.dot(array,array1)
print(array2)
print("Transpose of array2 is : \n",np.transpose(array2))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]
Transpose of array2 is : 
 [[ 24  78 132]
 [ 27  90 153]
 [ 30 102 174]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [2]:
#please provide your answer below this line.

import numpy as np
array = [[55,25,25],
              [30,44,2],
                  [11,45,77]]
matrix_length = len(array)
for i in range(matrix_length):
    print(array[i])
print("Determinant of array is :",np.linalg.det(array))

[55, 25, 25]
[30, 44, 2]
[11, 45, 77]
Determinant of array is : 145839.99999999994
