1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.


import numpy as np
array = np.random.randint(20,size=(3,3))
print(array)


[[ 5  3  1]
 [17  1 12]
 [10  1  3]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [3]:
#please provide your answer below this line.


import numpy as np 
array = np.arange(1,17).reshape(4,4)
array1 = np.arange(1,17).reshape(2,8)
array2 = np.vstack(array1)
print(array2)
array3 = np.arange(1,17).reshape(4,4)
array4=np.arange(1,17).reshape(2,8)
array5 = np.hstack(array4)
print(array5)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
