1. Create an 4x4 array containing the values ranging from 0 - 15 (use arange function). Then ,
  
  a) split it equally along horizontal.

  b) split it as 4 parts vertically.



In [2]:
#please provide your answer below this line

import numpy as np
array = np.arange(0,16).reshape(4,4)
print(array)
print(np.hsplit(array,4))
print(np.vsplit(array,4))



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


2. Create a 3x3 matrix using random module and then,

  a) Find the ceil of the matrix.
  
  b) Find the floor of the matrix.

In [3]:
#please provide your answer below this line

import numpy as np
array = np.random.randint(10,size=(3,3))
print(array)
print("\nCeil of the matrix is : \n ",np.ceil(array))
print("\nFloor of the matrix is : \n" , np.floor(array))


[[1 6 5]
 [1 6 2]
 [6 0 8]]

Ceil of the matrix is : 
  [[1. 6. 5.]
 [1. 6. 2.]
 [6. 0. 8.]]

Floor of the matrix is : 
 [[1. 6. 5.]
 [1. 6. 2.]
 [6. 0. 8.]]


3. Create a random 1x4 array and print the random array and its shape.
    
      (use the shape function for finding the shape & use the same random we created here for both the below operations.)

  a) Squeeze the random array and print the squeezed array and its shape.
  b) Expand the random array by one axis and print the expanded array and its shape.

In [4]:
#please provide your answer below this line.


import numpy as np
array = np.random.randint(10,size=(1,4))
print(array)
print(array.shape)
print(np.squeeze(array))
print(np.squeeze(array).shape)
print(np.expand_dims(array,axis=2))
print(np.expand_dims(array,axis=2).shape)


[[0 4 0 3]]
(1, 4)
[0 4 0 3]
(4,)
[[[0]
  [4]
  [0]
  [3]]]
(1, 4, 1)
