1. For the given ndarray b below, evaluate whether elements in array, b are equal to 'red'.Assign the result to b_bool and print the resultant boolean array.
b = np.array(["blue", "blue", "red", "blue"])

In [1]:
#please type your answer below this line.

import numpy as np
b = np.array(["blue", "blue", "red", "blue"])
bool_b=(b=="red")
print(bool_b)


[False False  True False]


2. Create two arrays on containing elements from 0-5 and another containing elements from 6-10. Then append this array.

In [3]:
#please type your answer below this line.

import numpy as np
arr1=np.array(np.arange(0,6))
arr2=np.array(np.arange(6,11))
arr3=np.append(arr1,arr2)
print(arr3)


[ 0  1  2  3  4  5  6  7  8  9 10]


3. Create a 2x4 array containing values from 0-7 and another 2x4 containing values from 8-15. Now append this with,

  a) axis as 0

  b) axis as 1

In [2]:
#please type your answer below this line.

import numpy as np
arr1=np.arange(0,8).reshape(2,4)
arr2=np.arange(8,16).reshape(2,4)
axis_0=np.append(arr1,arr2,axis=0)
print("axis 0 : ",axis_0)
axis_1=np.append(arr1,arr2,axis=1)
print("axis 1 : ",axis_1)


axis 0 :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
axis 1 :  [[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]
